### ISSUE TITLE
?

### ISSUE THREAD

**Issue by zhangjiaming-king** [SDchao/AutoVScodeCEnvironment#3]
过程：设置环境变量
信息：尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   在 System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   在 AutoVScodeCEnvironment.Classes.Operation.StartThread(String projectPath, Form_main mainForm)

**Comment by SDchao** [comment]
请右击那，选择以管理员权限运行程序

**Comment by SDchao** [comment]
请右击程序，选择以管理员权限运行
如果有杀毒软件请选择允许操作或者先行关闭
