### ISSUE TITLE
求助：安装时出现问题

### ISSUE THREAD

**Issue by 404582463** [SDchao/AutoVScodeCEnvironment#4]
您好，我是一个编程新人。为了配置vscode的C语言环境下载了您的分享。解压后根目录中只有名为AutoVScodeCEnvironment的sln后缀文件。我用vs 2017打开并编译后，可以进入安装程序。选择文件夹并执行安装后出现如下报错，请问该如何解决呢？
过程：创建文件索引
信息：Can not load 7-zip library or internal COM error! Message: DLL file does not exist.
   在 SevenZip.SevenZipLibraryManager.LoadLibrary(Object user, Enum format)
   在 SevenZip.SevenZipExtractor.Init(String archiveFullName)
   在 SevenZip.SevenZipExtractor..ctor(String archiveFullName)
   在 AutoVScodeCEnvironment.Classes.Operation.StartThread(String projectPath, Form_main mainForm) 位置 C:\Users\Administrator\Downloads\AutoVScodeCEnvironment-1.6\AutoVScodeCEnvironment-1.6\AutoVScodeCEnvironment\Classes\Operation.cs:行号 64

**Comment by SDchao** [comment]
你需要下载Release页面中的压缩包，而非源码文件。

**Comment by SDchao** [comment]
请访问下面的地址
https://github.com/SDchao/AutoVScodeCEnvironment/releases

**Comment by 404582463** [comment]
您好，我下载1.2版本的AutoVScodeCEnvironment.zip并且安装成功了，但是高于1.2的版本asset中只有2个原码文件，请问没有新版本的zip文件下载链接吗？

**Comment by SDchao** [comment]
因为github下载太慢，改为描述中的蓝奏云链接，注意查看

**Comment by 404582463** [comment]
非常感谢，问题已经解决！！
