### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by chaleni** [SDchao/AutoVScodeCEnvironment#7]
过程：设置环境变量
信息：尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   在 System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   在 AutoVScodeCEnvironment.Classes.Operation.StartThread(String projectPath, Form_main mainForm)

**Comment by SDchao** [comment]
注册表写入操作被拒绝
请用管理员权限运行。
