### ISSUE TITLE
过程：创建文件索引

### ISSUE THREAD

**Issue by Kwell** [SDchao/AutoVScodeCEnvironment#8]
过程：创建文件索引
信息：Can not load 7-zip library or internal COM error! Message: DLL file does not exist.
   在 SevenZip.SevenZipLibraryManager.LoadLibrary(Object user, Enum format)
   在 SevenZip.SevenZipExtractor.Init(String archiveFullName)
   在 SevenZip.SevenZipExtractor..ctor(String archiveFullName)
   在 AutoVScodeCEnvironment.Classes.Operation.StartThread(String projectPath, Form_main mainForm) 位置 D:\Private\AutoVScodeCEnvironment\AutoVScodeCEnvironment\Classes\Operation.cs:行号 64

**Comment by SDchao** [comment]
请解压后使用，确保7z.dll与exe文件在同一目录下
